---
- name: Install OS package pre-requisites
  become: true
  become_user: root
  package:
    name:
      - dconf-cli
      - dbus
      - python3-psutil
  when: dconf_settings | bool

- include_tasks: dconf.yml
  loop: "{{ dconf_settings }}"
